import { type CityGeo, CITY_GEO_FETCHED_ON, cityGeo } from "@/data/cities/geo.generated";

/**
 * ============================================================================
 * WORLDWIDE
 * ----------------------------------------------------------------------------
 * StudentOS answers questions about a city from official data, provider data
 * and student reports. None of those is limited to one continent, so the
 * product is usable in any city it lists from day one — what differs by city
 * is how deep the student layer already is.
 *
 *   depth  "deep"      a full city record exists in data/cities.ts: seeded
 *                      Pulse, price anchors, transport card, campuses.
 *          "live"      the AI, budget, map, places and arrival checklist all
 *                      work. Pulse is open but still filling up.
 *          "open"      everything works from official and provider data, and
 *                      the student layer starts the day the first student
 *                      posts.
 *
 * Nothing here claims a community that does not exist. `open` is the honest
 * default for the long tail, and the UI prints exactly that word.
 *
 * ---------------------------------------------------------------------------
 * THE FILE IS ASSEMBLED, NOT TYPED
 *
 * It used to be eighty hand-written rows repeating a currency and a timezone
 * per city, and it had no coordinates at all — which is why nothing in the
 * product could ask a question about the ground and why the map was a drawing.
 *
 * Now there are three inputs and each is the authority on one thing:
 *
 *   COUNTRIES  currency, formatting locale, languages a student will meet.
 *              One row per country rather than per city, because "Spain uses
 *              the euro" was previously stated eight times and could disagree
 *              with itself.
 *   CITY_ROWS  the editorial decisions: which cities are offered, what they
 *              are called in English, how deep our coverage is, and the
 *              timezone where a country spans more than one.
 *   cityGeo    coordinates and population, generated by
 *              `node scripts/import-cities.mjs` from Wikidata. Never edited by
 *              hand — see the header of the generated file.
 *
 * `build()` joins them and THROWS if a city has no geography. That is
 * deliberate and it fires at module load, so a city added without re-running
 * the import fails the build rather than shipping a city whose place search
 * has no origin and whose map opens in the Atlantic.
 * ============================================================================
 */

export type RegionKey = "europe" | "americas" | "apac" | "mea";

export type CoverageDepth = "deep" | "live" | "open";

/* -------------------------------------------------------------------------- */
/* Countries                                                                   */
/* -------------------------------------------------------------------------- */

type CountryProfile = {
  name: string;
  /** ISO-4217. Drives the price shown to a student in that country. */
  currency: string;
  /** BCP-47 tag used for number, date and currency formatting. */
  locale: string;
  /** Default IANA zone. Cities in a wider country override it below. */
  timezone: string;
  /** Languages a student will meet, most common first. */
  languages: readonly string[];
};

const COUNTRIES: Record<string, CountryProfile> = {
  ES: { name: "Spain", currency: "EUR", locale: "es-ES", timezone: "Europe/Madrid", languages: ["Spanish", "English"] },
  GB: { name: "United Kingdom", currency: "GBP", locale: "en-GB", timezone: "Europe/London", languages: ["English"] },
  NL: { name: "Netherlands", currency: "EUR", locale: "nl-NL", timezone: "Europe/Amsterdam", languages: ["Dutch", "English"] },
  DE: { name: "Germany", currency: "EUR", locale: "de-DE", timezone: "Europe/Berlin", languages: ["German", "English"] },
  FR: { name: "France", currency: "EUR", locale: "fr-FR", timezone: "Europe/Paris", languages: ["French", "English"] },
  PT: { name: "Portugal", currency: "EUR", locale: "pt-PT", timezone: "Europe/Lisbon", languages: ["Portuguese", "English"] },
  IT: { name: "Italy", currency: "EUR", locale: "it-IT", timezone: "Europe/Rome", languages: ["Italian", "English"] },
  BE: { name: "Belgium", currency: "EUR", locale: "fr-BE", timezone: "Europe/Brussels", languages: ["French", "Dutch", "English"] },
  AT: { name: "Austria", currency: "EUR", locale: "de-AT", timezone: "Europe/Vienna", languages: ["German", "English"] },
  HU: { name: "Hungary", currency: "HUF", locale: "hu-HU", timezone: "Europe/Budapest", languages: ["Hungarian", "English"] },
  FI: { name: "Finland", currency: "EUR", locale: "fi-FI", timezone: "Europe/Helsinki", languages: ["Finnish", "Swedish", "English"] },
  EE: { name: "Estonia", currency: "EUR", locale: "et-EE", timezone: "Europe/Tallinn", languages: ["Estonian", "English"] },
  DK: { name: "Denmark", currency: "DKK", locale: "da-DK", timezone: "Europe/Copenhagen", languages: ["Danish", "English"] },
  SE: { name: "Sweden", currency: "SEK", locale: "sv-SE", timezone: "Europe/Stockholm", languages: ["Swedish", "English"] },
  NO: { name: "Norway", currency: "NOK", locale: "nb-NO", timezone: "Europe/Oslo", languages: ["Norwegian", "English"] },
  PL: { name: "Poland", currency: "PLN", locale: "pl-PL", timezone: "Europe/Warsaw", languages: ["Polish", "English"] },
  CZ: { name: "Czechia", currency: "CZK", locale: "cs-CZ", timezone: "Europe/Prague", languages: ["Czech", "English"] },
  IE: { name: "Ireland", currency: "EUR", locale: "en-IE", timezone: "Europe/Dublin", languages: ["English", "Irish"] },
  CH: { name: "Switzerland", currency: "CHF", locale: "de-CH", timezone: "Europe/Zurich", languages: ["German", "French", "Italian", "English"] },
  TR: { name: "Türkiye", currency: "TRY", locale: "tr-TR", timezone: "Europe/Istanbul", languages: ["Turkish", "English"] },
  GR: { name: "Greece", currency: "EUR", locale: "el-GR", timezone: "Europe/Athens", languages: ["Greek", "English"] },
  AL: { name: "Albania", currency: "ALL", locale: "sq-AL", timezone: "Europe/Tirane", languages: ["Albanian", "English"] },
  AD: { name: "Andorra", currency: "EUR", locale: "ca-AD", timezone: "Europe/Andorra", languages: ["Catalan", "Spanish", "French"] },
  BY: { name: "Belarus", currency: "BYN", locale: "be-BY", timezone: "Europe/Minsk", languages: ["Belarusian", "Russian"] },
  BA: { name: "Bosnia and Herzegovina", currency: "BAM", locale: "bs-BA", timezone: "Europe/Sarajevo", languages: ["Bosnian", "Croatian", "Serbian", "English"] },
  BG: { name: "Bulgaria", currency: "BGN", locale: "bg-BG", timezone: "Europe/Sofia", languages: ["Bulgarian", "English"] },
  HR: { name: "Croatia", currency: "EUR", locale: "hr-HR", timezone: "Europe/Zagreb", languages: ["Croatian", "English"] },
  CY: { name: "Cyprus", currency: "EUR", locale: "el-CY", timezone: "Asia/Nicosia", languages: ["Greek", "English", "Turkish"] },
  IS: { name: "Iceland", currency: "ISK", locale: "is-IS", timezone: "Atlantic/Reykjavik", languages: ["Icelandic", "English"] },
  LV: { name: "Latvia", currency: "EUR", locale: "lv-LV", timezone: "Europe/Riga", languages: ["Latvian", "Russian", "English"] },
  LI: { name: "Liechtenstein", currency: "CHF", locale: "de-LI", timezone: "Europe/Vaduz", languages: ["German", "English"] },
  LT: { name: "Lithuania", currency: "EUR", locale: "lt-LT", timezone: "Europe/Vilnius", languages: ["Lithuanian", "English"] },
  LU: { name: "Luxembourg", currency: "EUR", locale: "fr-LU", timezone: "Europe/Luxembourg", languages: ["Luxembourgish", "French", "German", "English"] },
  MT: { name: "Malta", currency: "EUR", locale: "en-MT", timezone: "Europe/Malta", languages: ["Maltese", "English"] },
  MD: { name: "Moldova", currency: "MDL", locale: "ro-MD", timezone: "Europe/Chisinau", languages: ["Romanian", "Russian"] },
  MC: { name: "Monaco", currency: "EUR", locale: "fr-MC", timezone: "Europe/Monaco", languages: ["French", "English"] },
  ME: { name: "Montenegro", currency: "EUR", locale: "sr-ME", timezone: "Europe/Podgorica", languages: ["Montenegrin", "Serbian", "English"] },
  MK: { name: "North Macedonia", currency: "MKD", locale: "mk-MK", timezone: "Europe/Skopje", languages: ["Macedonian", "Albanian", "English"] },
  RO: { name: "Romania", currency: "RON", locale: "ro-RO", timezone: "Europe/Bucharest", languages: ["Romanian", "English"] },
  RS: { name: "Serbia", currency: "RSD", locale: "sr-RS", timezone: "Europe/Belgrade", languages: ["Serbian", "English"] },
  SK: { name: "Slovakia", currency: "EUR", locale: "sk-SK", timezone: "Europe/Bratislava", languages: ["Slovak", "English"] },
  SI: { name: "Slovenia", currency: "EUR", locale: "sl-SI", timezone: "Europe/Ljubljana", languages: ["Slovene", "English"] },
  UA: { name: "Ukraine", currency: "UAH", locale: "uk-UA", timezone: "Europe/Kyiv", languages: ["Ukrainian", "English"] },
  US: { name: "United States", currency: "USD", locale: "en-US", timezone: "America/New_York", languages: ["English", "Spanish"] },
  CA: { name: "Canada", currency: "CAD", locale: "en-CA", timezone: "America/Toronto", languages: ["English", "French"] },
  MX: { name: "Mexico", currency: "MXN", locale: "es-MX", timezone: "America/Mexico_City", languages: ["Spanish"] },
  BR: { name: "Brazil", currency: "BRL", locale: "pt-BR", timezone: "America/Sao_Paulo", languages: ["Portuguese"] },
  AR: { name: "Argentina", currency: "ARS", locale: "es-AR", timezone: "America/Argentina/Buenos_Aires", languages: ["Spanish"] },
  CL: { name: "Chile", currency: "CLP", locale: "es-CL", timezone: "America/Santiago", languages: ["Spanish"] },
  CO: { name: "Colombia", currency: "COP", locale: "es-CO", timezone: "America/Bogota", languages: ["Spanish"] },
  JP: { name: "Japan", currency: "JPY", locale: "ja-JP", timezone: "Asia/Tokyo", languages: ["Japanese", "English"] },
  KR: { name: "South Korea", currency: "KRW", locale: "ko-KR", timezone: "Asia/Seoul", languages: ["Korean", "English"] },
  SG: { name: "Singapore", currency: "SGD", locale: "en-SG", timezone: "Asia/Singapore", languages: ["English", "Mandarin", "Malay", "Tamil"] },
  HK: { name: "Hong Kong SAR", currency: "HKD", locale: "en-HK", timezone: "Asia/Hong_Kong", languages: ["Cantonese", "English"] },
  AU: { name: "Australia", currency: "AUD", locale: "en-AU", timezone: "Australia/Sydney", languages: ["English"] },
  NZ: { name: "New Zealand", currency: "NZD", locale: "en-NZ", timezone: "Pacific/Auckland", languages: ["English", "Māori"] },
  TH: { name: "Thailand", currency: "THB", locale: "th-TH", timezone: "Asia/Bangkok", languages: ["Thai", "English"] },
  MY: { name: "Malaysia", currency: "MYR", locale: "ms-MY", timezone: "Asia/Kuala_Lumpur", languages: ["Malay", "English"] },
  IN: { name: "India", currency: "INR", locale: "en-IN", timezone: "Asia/Kolkata", languages: ["Hindi", "English"] },
  TW: { name: "Taiwan", currency: "TWD", locale: "zh-TW", timezone: "Asia/Taipei", languages: ["Mandarin", "English"] },
  AE: { name: "United Arab Emirates", currency: "AED", locale: "en-AE", timezone: "Asia/Dubai", languages: ["Arabic", "English"] },
  QA: { name: "Qatar", currency: "QAR", locale: "en-QA", timezone: "Asia/Qatar", languages: ["Arabic", "English"] },
  IL: { name: "Israel", currency: "ILS", locale: "he-IL", timezone: "Asia/Jerusalem", languages: ["Hebrew", "English", "Arabic"] },
  EG: { name: "Egypt", currency: "EGP", locale: "ar-EG", timezone: "Africa/Cairo", languages: ["Arabic", "English"] },
  ZA: { name: "South Africa", currency: "ZAR", locale: "en-ZA", timezone: "Africa/Johannesburg", languages: ["English", "Afrikaans", "Zulu"] },
  KE: { name: "Kenya", currency: "KES", locale: "en-KE", timezone: "Africa/Nairobi", languages: ["Swahili", "English"] },
  NG: { name: "Nigeria", currency: "NGN", locale: "en-NG", timezone: "Africa/Lagos", languages: ["English"] },
  GH: { name: "Ghana", currency: "GHS", locale: "en-GH", timezone: "Africa/Accra", languages: ["English"] },
  MA: { name: "Morocco", currency: "MAD", locale: "fr-MA", timezone: "Africa/Casablanca", languages: ["Arabic", "French"] },
};

/** Languages a student will meet in a country. Used by the language layer. */
export function languagesInCountry(countryCode: string): readonly string[] {
  return COUNTRIES[countryCode]?.languages ?? ["English"];
}

/* -------------------------------------------------------------------------- */
/* Cities                                                                      */
/* -------------------------------------------------------------------------- */

type CityRow = {
  /** Joins to `cityGeo`. Also the URL slug for a city with a full record. */
  key: string;
  /** English display name. */
  name: string;
  countryCode: string;
  region: RegionKey;
  depth: CoverageDepth;
  /** Set when a full city record exists in data/cities.ts. */
  slug?: string;
  /** Where the country default is wrong for this city. */
  timezone?: string;
  /** Where the country default is wrong for this city. */
  locale?: string;
};

const CITY_ROWS: readonly CityRow[] = [
  /* --- Europe ----------------------------------------------------------- */
  { key: "madrid", name: "Madrid", countryCode: "ES", region: "europe", depth: "deep", slug: "madrid" },
  { key: "barcelona", name: "Barcelona", countryCode: "ES", region: "europe", depth: "deep", slug: "barcelona" },
  { key: "valencia", name: "Valencia", countryCode: "ES", region: "europe", depth: "open" },
  { key: "seville", name: "Seville", countryCode: "ES", region: "europe", depth: "open" },
  { key: "malaga", name: "Málaga", countryCode: "ES", region: "europe", depth: "open" },
  { key: "bilbao", name: "Bilbao", countryCode: "ES", region: "europe", depth: "open" },
  { key: "granada", name: "Granada", countryCode: "ES", region: "europe", depth: "open" },
  { key: "salamanca", name: "Salamanca", countryCode: "ES", region: "europe", depth: "open" },
  { key: "london", name: "London", countryCode: "GB", region: "europe", depth: "deep", slug: "london" },
  { key: "manchester", name: "Manchester", countryCode: "GB", region: "europe", depth: "open" },
  { key: "edinburgh", name: "Edinburgh", countryCode: "GB", region: "europe", depth: "open" },
  { key: "amsterdam", name: "Amsterdam", countryCode: "NL", region: "europe", depth: "deep", slug: "amsterdam" },
  { key: "rotterdam", name: "Rotterdam", countryCode: "NL", region: "europe", depth: "open" },
  { key: "utrecht", name: "Utrecht", countryCode: "NL", region: "europe", depth: "open" },
  { key: "berlin", name: "Berlin", countryCode: "DE", region: "europe", depth: "deep", slug: "berlin" },
  { key: "munich", name: "Munich", countryCode: "DE", region: "europe", depth: "open" },
  { key: "hamburg", name: "Hamburg", countryCode: "DE", region: "europe", depth: "open" },
  { key: "frankfurt", name: "Frankfurt", countryCode: "DE", region: "europe", depth: "open" },
  { key: "cologne", name: "Cologne", countryCode: "DE", region: "europe", depth: "open" },
  { key: "paris", name: "Paris", countryCode: "FR", region: "europe", depth: "live" },
  { key: "lyon", name: "Lyon", countryCode: "FR", region: "europe", depth: "open" },
  { key: "toulouse", name: "Toulouse", countryCode: "FR", region: "europe", depth: "open" },
  { key: "lisbon", name: "Lisbon", countryCode: "PT", region: "europe", depth: "live" },
  { key: "porto", name: "Porto", countryCode: "PT", region: "europe", depth: "open" },
  { key: "milan", name: "Milan", countryCode: "IT", region: "europe", depth: "live" },
  { key: "rome", name: "Rome", countryCode: "IT", region: "europe", depth: "open" },
  { key: "florence", name: "Florence", countryCode: "IT", region: "europe", depth: "open" },
  { key: "bologna", name: "Bologna", countryCode: "IT", region: "europe", depth: "open" },
  { key: "turin", name: "Turin", countryCode: "IT", region: "europe", depth: "open" },
  { key: "brussels", name: "Brussels", countryCode: "BE", region: "europe", depth: "open" },
  { key: "vienna", name: "Vienna", countryCode: "AT", region: "europe", depth: "open" },
  { key: "budapest", name: "Budapest", countryCode: "HU", region: "europe", depth: "open" },
  { key: "helsinki", name: "Helsinki", countryCode: "FI", region: "europe", depth: "open" },
  { key: "tallinn", name: "Tallinn", countryCode: "EE", region: "europe", depth: "open" },
  { key: "copenhagen", name: "Copenhagen", countryCode: "DK", region: "europe", depth: "open" },
  { key: "stockholm", name: "Stockholm", countryCode: "SE", region: "europe", depth: "open" },
  { key: "oslo", name: "Oslo", countryCode: "NO", region: "europe", depth: "open" },
  { key: "warsaw", name: "Warsaw", countryCode: "PL", region: "europe", depth: "open" },
  { key: "krakow", name: "Kraków", countryCode: "PL", region: "europe", depth: "open" },
  { key: "prague", name: "Prague", countryCode: "CZ", region: "europe", depth: "open" },
  { key: "dublin", name: "Dublin", countryCode: "IE", region: "europe", depth: "open" },
  { key: "zurich", name: "Zurich", countryCode: "CH", region: "europe", depth: "open" },
  { key: "istanbul", name: "Istanbul", countryCode: "TR", region: "europe", depth: "open" },
  { key: "athens", name: "Athens", countryCode: "GR", region: "europe", depth: "open" },
  { key: "zaragoza", name: "Zaragoza", countryCode: "ES", region: "europe", depth: "open" },
  { key: "murcia", name: "Murcia", countryCode: "ES", region: "europe", depth: "open" },
  { key: "alicante", name: "Alicante", countryCode: "ES", region: "europe", depth: "open" },
  { key: "santiago-de-compostela", name: "Santiago de Compostela", countryCode: "ES", region: "europe", depth: "open" },
  { key: "pamplona", name: "Pamplona", countryCode: "ES", region: "europe", depth: "open" },
  { key: "cordoba", name: "Córdoba", countryCode: "ES", region: "europe", depth: "open" },
  { key: "valladolid", name: "Valladolid", countryCode: "ES", region: "europe", depth: "open" },
  { key: "oviedo", name: "Oviedo", countryCode: "ES", region: "europe", depth: "open" },
  { key: "san-sebastian", name: "San Sebastián", countryCode: "ES", region: "europe", depth: "open" },
  { key: "palma", name: "Palma", countryCode: "ES", region: "europe", depth: "open" },
  { key: "birmingham", name: "Birmingham", countryCode: "GB", region: "europe", depth: "open" },
  { key: "leeds", name: "Leeds", countryCode: "GB", region: "europe", depth: "open" },
  { key: "glasgow", name: "Glasgow", countryCode: "GB", region: "europe", depth: "open" },
  { key: "liverpool", name: "Liverpool", countryCode: "GB", region: "europe", depth: "open" },
  { key: "bristol", name: "Bristol", countryCode: "GB", region: "europe", depth: "open" },
  { key: "nottingham", name: "Nottingham", countryCode: "GB", region: "europe", depth: "open" },
  { key: "sheffield", name: "Sheffield", countryCode: "GB", region: "europe", depth: "open" },
  { key: "newcastle", name: "Newcastle upon Tyne", countryCode: "GB", region: "europe", depth: "open" },
  { key: "oxford", name: "Oxford", countryCode: "GB", region: "europe", depth: "open" },
  { key: "cambridge", name: "Cambridge", countryCode: "GB", region: "europe", depth: "open" },
  { key: "cardiff", name: "Cardiff", countryCode: "GB", region: "europe", depth: "open" },
  { key: "coventry", name: "Coventry", countryCode: "GB", region: "europe", depth: "open" },
  { key: "southampton", name: "Southampton", countryCode: "GB", region: "europe", depth: "open" },
  { key: "aberdeen", name: "Aberdeen", countryCode: "GB", region: "europe", depth: "open" },
  { key: "belfast", name: "Belfast", countryCode: "GB", region: "europe", depth: "open" },
  { key: "york", name: "York", countryCode: "GB", region: "europe", depth: "open" },
  { key: "bath", name: "Bath", countryCode: "GB", region: "europe", depth: "open" },
  { key: "exeter", name: "Exeter", countryCode: "GB", region: "europe", depth: "open" },
  { key: "leicester", name: "Leicester", countryCode: "GB", region: "europe", depth: "open" },
  { key: "brighton", name: "Brighton", countryCode: "GB", region: "europe", depth: "open" },
  { key: "groningen", name: "Groningen", countryCode: "NL", region: "europe", depth: "open" },
  { key: "leiden", name: "Leiden", countryCode: "NL", region: "europe", depth: "open" },
  { key: "eindhoven", name: "Eindhoven", countryCode: "NL", region: "europe", depth: "open" },
  { key: "delft", name: "Delft", countryCode: "NL", region: "europe", depth: "open" },
  { key: "maastricht", name: "Maastricht", countryCode: "NL", region: "europe", depth: "open" },
  { key: "tilburg", name: "Tilburg", countryCode: "NL", region: "europe", depth: "open" },
  { key: "nijmegen", name: "Nijmegen", countryCode: "NL", region: "europe", depth: "open" },
  { key: "enschede", name: "Enschede", countryCode: "NL", region: "europe", depth: "open" },
  { key: "wageningen", name: "Wageningen", countryCode: "NL", region: "europe", depth: "open" },
  { key: "the-hague", name: "The Hague", countryCode: "NL", region: "europe", depth: "open" },
  { key: "heidelberg", name: "Heidelberg", countryCode: "DE", region: "europe", depth: "open" },
  { key: "leipzig", name: "Leipzig", countryCode: "DE", region: "europe", depth: "open" },
  { key: "dresden", name: "Dresden", countryCode: "DE", region: "europe", depth: "open" },
  { key: "stuttgart", name: "Stuttgart", countryCode: "DE", region: "europe", depth: "open" },
  { key: "dusseldorf", name: "Düsseldorf", countryCode: "DE", region: "europe", depth: "open" },
  { key: "aachen", name: "Aachen", countryCode: "DE", region: "europe", depth: "open" },
  { key: "bonn", name: "Bonn", countryCode: "DE", region: "europe", depth: "open" },
  { key: "freiburg", name: "Freiburg", countryCode: "DE", region: "europe", depth: "open" },
  { key: "munster", name: "Münster", countryCode: "DE", region: "europe", depth: "open" },
  { key: "gottingen", name: "Göttingen", countryCode: "DE", region: "europe", depth: "open" },
  { key: "tubingen", name: "Tübingen", countryCode: "DE", region: "europe", depth: "open" },
  { key: "mannheim", name: "Mannheim", countryCode: "DE", region: "europe", depth: "open" },
  { key: "karlsruhe", name: "Karlsruhe", countryCode: "DE", region: "europe", depth: "open" },
  { key: "nuremberg", name: "Nuremberg", countryCode: "DE", region: "europe", depth: "open" },
  { key: "bremen", name: "Bremen", countryCode: "DE", region: "europe", depth: "open" },
  { key: "hannover", name: "Hannover", countryCode: "DE", region: "europe", depth: "open" },
  { key: "bochum", name: "Bochum", countryCode: "DE", region: "europe", depth: "open" },
  { key: "darmstadt", name: "Darmstadt", countryCode: "DE", region: "europe", depth: "open" },
  { key: "jena", name: "Jena", countryCode: "DE", region: "europe", depth: "open" },
  { key: "konstanz", name: "Konstanz", countryCode: "DE", region: "europe", depth: "open" },
  { key: "marseille", name: "Marseille", countryCode: "FR", region: "europe", depth: "open" },
  { key: "bordeaux", name: "Bordeaux", countryCode: "FR", region: "europe", depth: "open" },
  { key: "lille", name: "Lille", countryCode: "FR", region: "europe", depth: "open" },
  { key: "montpellier", name: "Montpellier", countryCode: "FR", region: "europe", depth: "open" },
  { key: "nantes", name: "Nantes", countryCode: "FR", region: "europe", depth: "open" },
  { key: "strasbourg", name: "Strasbourg", countryCode: "FR", region: "europe", depth: "open" },
  { key: "grenoble", name: "Grenoble", countryCode: "FR", region: "europe", depth: "open" },
  { key: "nice", name: "Nice", countryCode: "FR", region: "europe", depth: "open" },
  { key: "rennes", name: "Rennes", countryCode: "FR", region: "europe", depth: "open" },
  { key: "aix-en-provence", name: "Aix-en-Provence", countryCode: "FR", region: "europe", depth: "open" },
  { key: "naples", name: "Naples", countryCode: "IT", region: "europe", depth: "open" },
  { key: "padua", name: "Padua", countryCode: "IT", region: "europe", depth: "open" },
  { key: "pisa", name: "Pisa", countryCode: "IT", region: "europe", depth: "open" },
  { key: "venice", name: "Venice", countryCode: "IT", region: "europe", depth: "open" },
  { key: "genoa", name: "Genoa", countryCode: "IT", region: "europe", depth: "open" },
  { key: "bari", name: "Bari", countryCode: "IT", region: "europe", depth: "open" },
  { key: "catania", name: "Catania", countryCode: "IT", region: "europe", depth: "open" },
  { key: "pavia", name: "Pavia", countryCode: "IT", region: "europe", depth: "open" },
  { key: "perugia", name: "Perugia", countryCode: "IT", region: "europe", depth: "open" },
  { key: "siena", name: "Siena", countryCode: "IT", region: "europe", depth: "open" },
  { key: "trento", name: "Trento", countryCode: "IT", region: "europe", depth: "open" },
  { key: "coimbra", name: "Coimbra", countryCode: "PT", region: "europe", depth: "open" },
  { key: "braga", name: "Braga", countryCode: "PT", region: "europe", depth: "open" },
  { key: "aveiro", name: "Aveiro", countryCode: "PT", region: "europe", depth: "open" },
  { key: "leuven", name: "Leuven", countryCode: "BE", region: "europe", depth: "open" },
  { key: "ghent", name: "Ghent", countryCode: "BE", region: "europe", depth: "open" },
  { key: "antwerp", name: "Antwerp", countryCode: "BE", region: "europe", depth: "open" },
  { key: "liege", name: "Liège", countryCode: "BE", region: "europe", depth: "open" },
  { key: "louvain-la-neuve", name: "Louvain-la-Neuve", countryCode: "BE", region: "europe", depth: "open" },
  { key: "graz", name: "Graz", countryCode: "AT", region: "europe", depth: "open" },
  { key: "innsbruck", name: "Innsbruck", countryCode: "AT", region: "europe", depth: "open" },
  { key: "salzburg", name: "Salzburg", countryCode: "AT", region: "europe", depth: "open" },
  { key: "linz", name: "Linz", countryCode: "AT", region: "europe", depth: "open" },
  { key: "geneva", name: "Geneva", countryCode: "CH", region: "europe", depth: "open" },
  { key: "lausanne", name: "Lausanne", countryCode: "CH", region: "europe", depth: "open" },
  { key: "bern", name: "Bern", countryCode: "CH", region: "europe", depth: "open" },
  { key: "basel", name: "Basel", countryCode: "CH", region: "europe", depth: "open" },
  { key: "st-gallen", name: "St. Gallen", countryCode: "CH", region: "europe", depth: "open" },
  { key: "lugano", name: "Lugano", countryCode: "CH", region: "europe", depth: "open" },
  { key: "cork", name: "Cork", countryCode: "IE", region: "europe", depth: "open" },
  { key: "galway", name: "Galway", countryCode: "IE", region: "europe", depth: "open" },
  { key: "limerick", name: "Limerick", countryCode: "IE", region: "europe", depth: "open" },
  { key: "maynooth", name: "Maynooth", countryCode: "IE", region: "europe", depth: "open" },
  { key: "aarhus", name: "Aarhus", countryCode: "DK", region: "europe", depth: "open" },
  { key: "odense", name: "Odense", countryCode: "DK", region: "europe", depth: "open" },
  { key: "aalborg", name: "Aalborg", countryCode: "DK", region: "europe", depth: "open" },
  { key: "gothenburg", name: "Gothenburg", countryCode: "SE", region: "europe", depth: "open" },
  { key: "lund", name: "Lund", countryCode: "SE", region: "europe", depth: "open" },
  { key: "uppsala", name: "Uppsala", countryCode: "SE", region: "europe", depth: "open" },
  { key: "malmo", name: "Malmö", countryCode: "SE", region: "europe", depth: "open" },
  { key: "linkoping", name: "Linköping", countryCode: "SE", region: "europe", depth: "open" },
  { key: "umea", name: "Umeå", countryCode: "SE", region: "europe", depth: "open" },
  { key: "bergen", name: "Bergen", countryCode: "NO", region: "europe", depth: "open" },
  { key: "trondheim", name: "Trondheim", countryCode: "NO", region: "europe", depth: "open" },
  { key: "tromso", name: "Tromsø", countryCode: "NO", region: "europe", depth: "open" },
  { key: "tampere", name: "Tampere", countryCode: "FI", region: "europe", depth: "open" },
  { key: "turku", name: "Turku", countryCode: "FI", region: "europe", depth: "open" },
  { key: "oulu", name: "Oulu", countryCode: "FI", region: "europe", depth: "open" },
  { key: "jyvaskyla", name: "Jyväskylä", countryCode: "FI", region: "europe", depth: "open" },
  { key: "tartu", name: "Tartu", countryCode: "EE", region: "europe", depth: "open" },
  { key: "wroclaw", name: "Wrocław", countryCode: "PL", region: "europe", depth: "open" },
  { key: "poznan", name: "Poznań", countryCode: "PL", region: "europe", depth: "open" },
  { key: "gdansk", name: "Gdańsk", countryCode: "PL", region: "europe", depth: "open" },
  { key: "lodz", name: "Łódź", countryCode: "PL", region: "europe", depth: "open" },
  { key: "lublin", name: "Lublin", countryCode: "PL", region: "europe", depth: "open" },
  { key: "katowice", name: "Katowice", countryCode: "PL", region: "europe", depth: "open" },
  { key: "brno", name: "Brno", countryCode: "CZ", region: "europe", depth: "open" },
  { key: "olomouc", name: "Olomouc", countryCode: "CZ", region: "europe", depth: "open" },
  { key: "ostrava", name: "Ostrava", countryCode: "CZ", region: "europe", depth: "open" },
  { key: "debrecen", name: "Debrecen", countryCode: "HU", region: "europe", depth: "open" },
  { key: "szeged", name: "Szeged", countryCode: "HU", region: "europe", depth: "open" },
  { key: "pecs", name: "Pécs", countryCode: "HU", region: "europe", depth: "open" },
  { key: "thessaloniki", name: "Thessaloniki", countryCode: "GR", region: "europe", depth: "open" },
  { key: "patras", name: "Patras", countryCode: "GR", region: "europe", depth: "open" },
  { key: "heraklion", name: "Heraklion", countryCode: "GR", region: "europe", depth: "open" },
  { key: "ankara", name: "Ankara", countryCode: "TR", region: "europe", depth: "open" },
  { key: "izmir", name: "Izmir", countryCode: "TR", region: "europe", depth: "open" },
  { key: "antalya", name: "Antalya", countryCode: "TR", region: "europe", depth: "open" },
  { key: "bucharest", name: "Bucharest", countryCode: "RO", region: "europe", depth: "open" },
  { key: "cluj-napoca", name: "Cluj-Napoca", countryCode: "RO", region: "europe", depth: "open" },
  { key: "timisoara", name: "Timișoara", countryCode: "RO", region: "europe", depth: "open" },
  { key: "iasi", name: "Iași", countryCode: "RO", region: "europe", depth: "open" },
  { key: "brasov", name: "Brașov", countryCode: "RO", region: "europe", depth: "open" },
  { key: "sofia", name: "Sofia", countryCode: "BG", region: "europe", depth: "open" },
  { key: "plovdiv", name: "Plovdiv", countryCode: "BG", region: "europe", depth: "open" },
  { key: "varna", name: "Varna", countryCode: "BG", region: "europe", depth: "open" },
  { key: "zagreb", name: "Zagreb", countryCode: "HR", region: "europe", depth: "open" },
  { key: "split", name: "Split", countryCode: "HR", region: "europe", depth: "open" },
  { key: "rijeka", name: "Rijeka", countryCode: "HR", region: "europe", depth: "open" },
  { key: "osijek", name: "Osijek", countryCode: "HR", region: "europe", depth: "open" },
  { key: "belgrade", name: "Belgrade", countryCode: "RS", region: "europe", depth: "open" },
  { key: "novi-sad", name: "Novi Sad", countryCode: "RS", region: "europe", depth: "open" },
  { key: "nis", name: "Niš", countryCode: "RS", region: "europe", depth: "open" },
  { key: "bratislava", name: "Bratislava", countryCode: "SK", region: "europe", depth: "open" },
  { key: "kosice", name: "Košice", countryCode: "SK", region: "europe", depth: "open" },
  { key: "ljubljana", name: "Ljubljana", countryCode: "SI", region: "europe", depth: "open" },
  { key: "maribor", name: "Maribor", countryCode: "SI", region: "europe", depth: "open" },
  { key: "vilnius", name: "Vilnius", countryCode: "LT", region: "europe", depth: "open" },
  { key: "kaunas", name: "Kaunas", countryCode: "LT", region: "europe", depth: "open" },
  { key: "klaipeda", name: "Klaipėda", countryCode: "LT", region: "europe", depth: "open" },
  { key: "riga", name: "Riga", countryCode: "LV", region: "europe", depth: "open" },
  { key: "kyiv", name: "Kyiv", countryCode: "UA", region: "europe", depth: "open" },
  { key: "lviv", name: "Lviv", countryCode: "UA", region: "europe", depth: "open" },
  { key: "kharkiv", name: "Kharkiv", countryCode: "UA", region: "europe", depth: "open" },
  { key: "nicosia", name: "Nicosia", countryCode: "CY", region: "europe", depth: "open" },
  { key: "limassol", name: "Limassol", countryCode: "CY", region: "europe", depth: "open" },
  { key: "valletta", name: "Valletta", countryCode: "MT", region: "europe", depth: "open" },
  { key: "msida", name: "Msida", countryCode: "MT", region: "europe", depth: "open" },
  { key: "luxembourg-city", name: "Luxembourg", countryCode: "LU", region: "europe", depth: "open" },
  { key: "reykjavik", name: "Reykjavík", countryCode: "IS", region: "europe", depth: "open" },
  { key: "sarajevo", name: "Sarajevo", countryCode: "BA", region: "europe", depth: "open" },
  { key: "banja-luka", name: "Banja Luka", countryCode: "BA", region: "europe", depth: "open" },
  { key: "mostar", name: "Mostar", countryCode: "BA", region: "europe", depth: "open" },
  { key: "skopje", name: "Skopje", countryCode: "MK", region: "europe", depth: "open" },
  { key: "tirana", name: "Tirana", countryCode: "AL", region: "europe", depth: "open" },
  { key: "podgorica", name: "Podgorica", countryCode: "ME", region: "europe", depth: "open" },
  { key: "chisinau", name: "Chișinău", countryCode: "MD", region: "europe", depth: "open" },
  { key: "minsk", name: "Minsk", countryCode: "BY", region: "europe", depth: "open" },
  { key: "andorra-la-vella", name: "Andorra la Vella", countryCode: "AD", region: "europe", depth: "open" },
  { key: "vaduz", name: "Vaduz", countryCode: "LI", region: "europe", depth: "open" },
  { key: "monaco", name: "Monaco", countryCode: "MC", region: "europe", depth: "open" },
  /* --- Americas --------------------------------------------------------- */
  { key: "new-york", name: "New York", countryCode: "US", region: "americas", depth: "live" },
  { key: "boston", name: "Boston", countryCode: "US", region: "americas", depth: "live" },
  { key: "chicago", name: "Chicago", countryCode: "US", region: "americas", depth: "open", timezone: "America/Chicago" },
  { key: "los-angeles", name: "Los Angeles", countryCode: "US", region: "americas", depth: "open", timezone: "America/Los_Angeles" },
  { key: "austin", name: "Austin", countryCode: "US", region: "americas", depth: "open", timezone: "America/Chicago" },
  { key: "toronto", name: "Toronto", countryCode: "CA", region: "americas", depth: "live" },
  { key: "montreal", name: "Montreal", countryCode: "CA", region: "americas", depth: "open", locale: "fr-CA" },
  { key: "vancouver", name: "Vancouver", countryCode: "CA", region: "americas", depth: "open", timezone: "America/Vancouver" },
  { key: "mexico-city", name: "Mexico City", countryCode: "MX", region: "americas", depth: "open" },
  { key: "sao-paulo", name: "São Paulo", countryCode: "BR", region: "americas", depth: "open" },
  { key: "buenos-aires", name: "Buenos Aires", countryCode: "AR", region: "americas", depth: "open" },
  { key: "santiago", name: "Santiago", countryCode: "CL", region: "americas", depth: "open" },
  { key: "bogota", name: "Bogotá", countryCode: "CO", region: "americas", depth: "open" },
  /* --- Asia Pacific ----------------------------------------------------- */
  { key: "tokyo", name: "Tokyo", countryCode: "JP", region: "apac", depth: "live" },
  { key: "seoul", name: "Seoul", countryCode: "KR", region: "apac", depth: "live" },
  { key: "singapore", name: "Singapore", countryCode: "SG", region: "apac", depth: "live" },
  { key: "hong-kong", name: "Hong Kong", countryCode: "HK", region: "apac", depth: "open" },
  { key: "sydney", name: "Sydney", countryCode: "AU", region: "apac", depth: "live" },
  { key: "melbourne", name: "Melbourne", countryCode: "AU", region: "apac", depth: "open", timezone: "Australia/Melbourne" },
  { key: "auckland", name: "Auckland", countryCode: "NZ", region: "apac", depth: "open" },
  { key: "bangkok", name: "Bangkok", countryCode: "TH", region: "apac", depth: "open" },
  { key: "kuala-lumpur", name: "Kuala Lumpur", countryCode: "MY", region: "apac", depth: "open" },
  { key: "delhi", name: "Delhi", countryCode: "IN", region: "apac", depth: "open" },
  { key: "bengaluru", name: "Bengaluru", countryCode: "IN", region: "apac", depth: "open" },
  { key: "taipei", name: "Taipei", countryCode: "TW", region: "apac", depth: "open" },
  /* --- Middle East & Africa --------------------------------------------- */
  { key: "dubai", name: "Dubai", countryCode: "AE", region: "mea", depth: "live" },
  { key: "abu-dhabi", name: "Abu Dhabi", countryCode: "AE", region: "mea", depth: "open" },
  { key: "doha", name: "Doha", countryCode: "QA", region: "mea", depth: "open" },
  { key: "tel-aviv", name: "Tel Aviv", countryCode: "IL", region: "mea", depth: "open" },
  { key: "cairo", name: "Cairo", countryCode: "EG", region: "mea", depth: "open" },
  { key: "cape-town", name: "Cape Town", countryCode: "ZA", region: "mea", depth: "open" },
  { key: "johannesburg", name: "Johannesburg", countryCode: "ZA", region: "mea", depth: "open" },
  { key: "nairobi", name: "Nairobi", countryCode: "KE", region: "mea", depth: "open" },
  { key: "lagos", name: "Lagos", countryCode: "NG", region: "mea", depth: "open" },
  { key: "accra", name: "Accra", countryCode: "GH", region: "mea", depth: "open" },
  { key: "casablanca", name: "Casablanca", countryCode: "MA", region: "mea", depth: "open" },
];

/* -------------------------------------------------------------------------- */
/* Assembly                                                                    */
/* -------------------------------------------------------------------------- */

export type CoverageCity = {
  /** Stable identifier. Joins the editorial row to its geography. */
  key: string;
  name: string;
  country: string;
  /** ISO-3166 alpha-2. */
  countryCode: string;
  /** ISO-4217. Drives the price shown to a student in that city. */
  currency: string;
  /** BCP-47 tag used for number, date and currency formatting. */
  locale: string;
  /** IANA timezone. The planner needs it before it can say "tonight". */
  timezone: string;
  languages: readonly string[];
  depth: CoverageDepth;
  /** Set when a full city record exists, so the card can link to it. */
  slug?: string;
  /** City centre, from Wikidata. The origin of every place search. */
  lat: number;
  lng: number;
  /** https://www.wikidata.org/wiki/<id> — provenance for lat, lng, population. */
  wikidataId: string;
  /** Municipality population where Wikidata states one. Never a student count. */
  population: number | null;
};

const GEO_BY_KEY = new Map<string, CityGeo>(cityGeo.map((row) => [row.key, row]));

function build(): CoverageCity[] {
  return CITY_ROWS.map((row) => {
    const country = COUNTRIES[row.countryCode];
    if (!country) {
      throw new Error(`regions: ${row.key} has no country profile for ${row.countryCode}`);
    }
    const geo = GEO_BY_KEY.get(row.key);
    if (!geo) {
      /* Loud on purpose, at module load, so it fails the build. A city with no
         coordinate has no place search, no map and no distance to anything,
         and every one of those failures is silent at runtime. */
      throw new Error(
        `regions: ${row.key} has no geography. Run "node scripts/import-cities.mjs" after adding a city.`,
      );
    }

    return {
      key: row.key,
      name: row.name,
      country: country.name,
      countryCode: row.countryCode,
      currency: country.currency,
      locale: row.locale ?? country.locale,
      timezone: row.timezone ?? country.timezone,
      languages: country.languages,
      depth: row.depth,
      ...(row.slug ? { slug: row.slug } : {}),
      lat: geo.lat,
      lng: geo.lng,
      wikidataId: geo.wikidataId,
      population: geo.population,
    };
  });
}

export const allCoverageCities: readonly CoverageCity[] = Object.freeze(build());

export const coverageDepthLabel: Record<CoverageDepth, string> = {
  deep: "Full city",
  live: "Pulse open",
  open: "Open",
};

export const coverageDepthNote: Record<CoverageDepth, string> = {
  deep: "Price anchors, transport card, campuses and an arrival checklist, on top of live map data.",
  live: "Everything works. The student layer is still filling up.",
  open: "Map, places, budget and arrival work from provider and official data on day one.",
};

export type Region = {
  key: RegionKey;
  label: string;
  /** One line on what makes student life in this region distinct. */
  note: string;
  cities: readonly CoverageCity[];
};

const REGION_META: Record<RegionKey, { label: string; note: string }> = {
  europe: {
    label: "Europe",
    note: "Erasmus moves roughly 300,000 students a year between these cities. Transport passes and free-museum windows are where the money is won.",
  },
  americas: {
    label: "Americas",
    note: "Campus-centred rather than city-centred, and the transport question is usually whether you need a car at all.",
  },
  apac: {
    label: "Asia Pacific",
    note: "The widest spread of student costs anywhere: the same evening can be a tenth of the price two flights away.",
  },
  mea: {
    label: "Middle East & Africa",
    note: "Fast-growing international campuses, and the cities where an official source matters most because listings go out of date quickest.",
  },
};

export const regions: readonly Region[] = (
  Object.keys(REGION_META) as RegionKey[]
).map((key) => ({
  key,
  label: REGION_META[key].label,
  note: REGION_META[key].note,
  cities: allCoverageCities.filter(
    (city) => CITY_ROWS.find((row) => row.key === city.key)?.region === key,
  ),
}));

/** Distinct currencies the price and budget layers already format correctly. */
export const supportedCurrencies: readonly string[] = Array.from(
  new Set(allCoverageCities.map((city) => city.currency)),
).sort();

/** Distinct locales, which is also the list of number and date formats. */
export const supportedLocales: readonly string[] = Array.from(
  new Set(allCoverageCities.map((city) => city.locale)),
).sort();

/**
 * Interface languages. Kept separate from `supportedLocales` on purpose: a
 * student in Tokyo can read the app in English while every price, date and fare
 * renders in yen and Japanese formatting. Conflating the two is how products
 * end up showing euro prices to someone standing in Seoul.
 */
export const interfaceLanguages = [
  { code: "en", label: "English", endonym: "English" },
  { code: "es", label: "Spanish", endonym: "Español" },
  { code: "fr", label: "French", endonym: "Français" },
  { code: "de", label: "German", endonym: "Deutsch" },
  { code: "pt", label: "Portuguese", endonym: "Português" },
  { code: "it", label: "Italian", endonym: "Italiano" },
  { code: "nl", label: "Dutch", endonym: "Nederlands" },
  { code: "pl", label: "Polish", endonym: "Polski" },
  { code: "tr", label: "Turkish", endonym: "Türkçe" },
  { code: "ar", label: "Arabic", endonym: "العربية", rtl: true },
  { code: "he", label: "Hebrew", endonym: "עברית", rtl: true },
  { code: "zh", label: "Chinese", endonym: "中文" },
  { code: "ja", label: "Japanese", endonym: "日本語" },
  { code: "ko", label: "Korean", endonym: "한국어" },
  { code: "hi", label: "Hindi", endonym: "हिन्दी" },
  { code: "th", label: "Thai", endonym: "ไทย" },
] as const;

export const rtlLanguages = interfaceLanguages
  .filter((language) => "rtl" in language && language.rtl)
  .map((language) => language.code);

export function citiesForRegion(key: RegionKey): readonly CoverageCity[] {
  return regions.find((region) => region.key === key)?.cities ?? [];
}

export function findCoverageCity(name: string): CoverageCity | undefined {
  const needle = name.trim().toLowerCase();
  return allCoverageCities.find(
    (city) => city.name.toLowerCase() === needle || city.key === needle,
  );
}

export function coverageCityByKey(key: string): CoverageCity | undefined {
  return allCoverageCities.find((city) => city.key === key);
}

/**
 * Counts printed in the coverage UI. Derived, never typed by hand, so the
 * headline can never drift from the list underneath it.
 */
export const coverageStats = {
  regions: regions.length,
  cities: allCoverageCities.length,
  countries: new Set(allCoverageCities.map((city) => city.countryCode)).size,
  currencies: supportedCurrencies.length,
  languages: interfaceLanguages.length,
  deepCities: allCoverageCities.filter((city) => city.depth === "deep").length,
  /** When the coordinates behind every city were last imported. */
  geographyFetchedOn: CITY_GEO_FETCHED_ON,
} as const;
