#!/usr/bin/env node
/**
 * ============================================================================
 * THE SQL TO ACTUALLY RUN
 * ----------------------------------------------------------------------------
 * Prints exactly the migrations a new Supabase project needs, in order, and
 * nothing else.
 *
 *   pnpm db:sql                 # everything, ready to paste
 *   pnpm db:sql --core          # 0005 only, if pg_cron is unavailable
 *   pnpm db:sql --out setup.sql # write it to a file instead
 *
 * WHY THIS EXISTS, and it is not convenience. `supabase/migrations/` holds seven
 * files and **four of them must never be applied**. 0001 to 0004 describe the
 * relational schema the product is heading towards -- a real table per concept,
 * with foreign keys and per-row policies -- and nothing in the application
 * reads them. Applying them creates a few dozen empty tables that look
 * authoritative, sit next to the one table that is actually used, and mislead
 * the next person who opens the database wondering where the data is.
 *
 * The obvious instinct on seeing a migrations directory is to run all of it.
 * Here that instinct is wrong, the failure is silent, and the only thing
 * standing between it and a confused afternoon was a sentence in a checklist.
 * This command is that sentence made executable: run it, paste what it gives
 * you, and the question does not arise.
 *
 * WHAT EACH ONE DOES
 *
 *   0005  The row store. This is the one that matters. Without it the product
 *         runs on a JSON file that a redeploy deletes, which on Vercel means
 *         every account created since the last deploy is gone.
 *
 *   0006  Scheduled cleanup, through pg_cron: expired sessions, spent password
 *         tokens, the Stripe idempotency ledger, the AI usage log. Two of those
 *         are hashed credentials with no remaining purpose, so this is a
 *         security measure and not only housekeeping. It needs the `pg_cron`
 *         extension, which some plans do not offer -- hence `--core`, which
 *         omits it. The product runs correctly without it; those four kinds of
 *         row simply accumulate until something prunes them.
 *
 *   0007  The shared rate limit. One counter every instance can see, instead of
 *         one per serverless isolate. Without it the sign-in and sign-up
 *         ceilings are per isolate, and the isolate count is chosen by the
 *         traffic an attacker is generating -- so the ceiling that guards
 *         password guessing effectively is not one. Also needs `pg_cron`, for
 *         an hourly prune, so it is outside `--core` for the same reason 0006
 *         is; the table and both functions still work without the schedule.
 * ============================================================================
 */

import { readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const MIGRATIONS = join(ROOT, "supabase", "migrations");

const FILES = [
  { name: "0005_row_store.sql", label: "the row store", core: true },
  { name: "0006_scheduled_cleanup.sql", label: "scheduled cleanup (needs pg_cron)", core: false },
  { name: "0007_shared_rate_limit.sql", label: "shared rate limit (needs pg_cron)", core: false },
];

/** Migrations that exist and must not be run. Named so the answer is on record. */
const NOT_APPLIED = ["0001_init.sql", "0002_daily_product.sql", "0003_operations.sql", "0004_lifeops_missions_exchange.sql"];

const args = process.argv.slice(2);
const coreOnly = args.includes("--core");
const outIndex = args.indexOf("--out");
const outPath = outIndex >= 0 ? args[outIndex + 1] : null;

const wanted = FILES.filter((file) => (coreOnly ? file.core : true));

const banner = `-- ===========================================================================
-- StudentOS - Supabase setup
-- ---------------------------------------------------------------------------
-- Generated by \`pnpm db:sql\`${coreOnly ? " --core" : ""}. Paste the whole thing into the SQL editor
-- (Supabase dashboard -> SQL Editor -> New query) and run it once.
--
-- Contains, in this order:
${wanted.map((file) => `--   ${file.name}  -- ${file.label}`).join("\n")}
--
-- DELIBERATELY NOT INCLUDED, and they must not be run:
${NOT_APPLIED.map((name) => `--   ${name}`).join("\n")}
--
-- Those four declare the relational schema the product is moving towards. No
-- code reads them. Applying them creates empty tables that look authoritative
-- and mislead whoever next opens this database.
--
-- Everything below is idempotent - \`create table if not exists\`,
-- \`create or replace function\` - so running it twice is safe.
--
-- Afterwards, prove it works rather than assuming:  pnpm db:verify
-- ===========================================================================

`;

const parts = [banner];

for (const file of wanted) {
  let sql;
  try {
    sql = await readFile(join(MIGRATIONS, file.name), "utf8");
  } catch (error) {
    console.error(`Could not read ${file.name}: ${error.message}`);
    process.exit(1);
  }

  parts.push(
    `\n-- ===========================================================================\n` +
      `-- ${file.name}\n` +
      `-- ===========================================================================\n\n`,
  );
  parts.push(sql.endsWith("\n") ? sql : `${sql}\n`);
}

const output = parts.join("");

if (outPath) {
  await writeFile(outPath, output, "utf8");
  console.error(`Wrote ${outPath} (${wanted.length} migration(s), ${output.length} bytes)`);
  console.error(`Next: paste it into the Supabase SQL editor, then run \`pnpm db:verify\`.`);
} else {
  /* The SQL goes to stdout and every human-readable word to stderr, so
     `pnpm db:sql > setup.sql` produces a file that is only SQL. */
  process.stdout.write(output);
  console.error("");
  console.error(`  ${wanted.length} migration(s) above.${coreOnly ? " (--core: pg_cron cleanup omitted)" : ""}`);
  console.error("  Paste into the Supabase SQL editor, run once, then: pnpm db:verify");
  console.error("");
}
